In [3]:
import numpy as np
import math

In [4]:
intrinsic_mat = [[951.07990705,   0.,         691.,        ],
 [  0.,         951.07990705, 256.        ],
 [  0. ,          0. ,          1.        ]]

In [5]:
 ravel_mode = 'C'
 P0 = intrinsic_mat
 P0 = np.column_stack((P0, np.array([0, 0, 0])))
 P0 = np.ravel(P0, order=ravel_mode)

In [6]:
P0

array([951.07990705,   0.        , 691.        ,   0.        ,
         0.        , 951.07990705, 256.        ,   0.        ,
         0.        ,   0.        ,   1.        ,   0.        ])

In [7]:
w=1382
h=512
fov=72.0

width = w#int(camera.attributes['image_size_x'])
height = h#int(camera.attributes['image_size_y'])
fov = fov#float(camera.attributes['fov'])

k = np.identity(3)
k[0, 2] = width / 2.0
k[1, 2] = height / 2.0
k[0, 0] = k[1, 1] = width / (2.0 * np.tan(fov * np.pi / 360.0))

ravel_mode = 'C'
intrinsic_mat =   k
P0 = intrinsic_mat
P0 = np.column_stack((P0, np.array([0, 0, 0])))
P0 = np.ravel(P0, order=ravel_mode)
P0

array([951.07990705,   0.        , 691.        ,   0.        ,
         0.        , 951.07990705, 256.        ,   0.        ,
         0.        ,   0.        ,   1.        ,   0.        ])

In [11]:
fx = 1392/(2*math.tan((72.0/2.0)*(math.pi/180.0)))
fy = fx
cu = 1392/2.0
cv = 1024/2.0
K = np.array([[fx,0,cu,0],[0,fy,cv,0],[0,0,1,0]])
K


array([[957.96181665,   0.        , 696.        ,   0.        ],
       [  0.        , 957.96181665, 512.        ,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ]])

In [1]:
pwd

'/home/chirathv97/FYP/Stereo-Vision-Based-Vehicle-Forward-Collision-Warning-System'

In [9]:
from PIL import Image

In [22]:
imgs_path='./data/carla_s1_left/'
rgb_values = np.concatenate(
    [Image.open(img).getdata() for img in imgs_path], 
    axis=0
) / 255.

# rgb_values.shape == (n, 3), 
# where n is the total number of pixels in all images, 
# and 3 are the 3 channels: R, G, B.

# Each value is in the interval [0; 1]

mu_rgb = np.mean(rgb_values, axis=0)  # mu_rgb.shape == (3,)
std_rgb = np.std(rgb_values, axis=0)  # std_rgb.shape == (3,)

IsADirectoryError: [Errno 21] Is a directory: '.'

In [23]:
import cv2
import numpy as np

# Read the image
image = cv2.imread('./data/carla_s1_left/000000.png')

# Convert the image to RGB format
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Calculate the mean and standard deviation of RGB values
mean = np.mean(image, axis=(0, 1))
std_dev = np.std(image, axis=(0, 1))

print("Mean RGB values:", mean)
print("Standard Deviation RGB values:", std_dev)

Mean RGB values: [126.09847209 115.99696655 109.35708008]
Standard Deviation RGB values: [43.8449893  44.39304006 42.75420711]


In [27]:
import cv2
import numpy as np
import os

# Path to the folder containing the images
folder_path = './data/local_s1_left'

# Initialize empty lists for storing mean and standard deviation values
mean_values = []
std_dev_values = []

# Iterate over each file in the folder
for filename in os.listdir(folder_path):
    if filename.endswith('.jpg') or filename.endswith('.png'):  # Modify extensions as needed
        # Read the image
        image_path = os.path.join(folder_path, filename)
        image = cv2.imread(image_path)
        
        # Convert the image to RGB format
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        # Calculate the mean and standard deviation of RGB values
        mean = np.mean(image, axis=(0, 1))
        std_dev = np.std(image, axis=(0, 1))
        
        # Append the mean and standard deviation values to the lists
        mean_values.append(mean)
        std_dev_values.append(std_dev)

# Convert the lists to NumPy arrays
mean_values = np.array(mean_values)
std_dev_values = np.array(std_dev_values)

# Calculate the overall mean and standard deviation across all images
overall_mean = np.mean(mean_values, axis=0)
overall_std_dev = np.mean(std_dev_values, axis=0)

print("Overall Mean RGB values:", overall_mean)
print("Overall Standard Deviation RGB values:", overall_std_dev)


Overall Mean RGB values: [126.10772444 139.22664283 133.02220988]
Overall Standard Deviation RGB values: [59.76229321 64.77861987 70.3936116 ]


In [28]:
overall_std_dev/255

array([0.23436193, 0.2540338 , 0.27605338])

In [29]:
overall_mean/255

array([0.4945401 , 0.54598683, 0.52165573])